-- Fix Communities Table - Remove Duplicate Indexes and Constraints
-- This script fixes the "Too many keys specified; max 64 keys allowed" error

USE loomio_db;

-- Drop all duplicate unique constraints on community_code (keep only the first one)
ALTER TABLE communities DROP INDEX community_code_2;
ALTER TABLE communities DROP INDEX community_code_3;
ALTER TABLE communities DROP INDEX community_code_4;
ALTER TABLE communities DROP INDEX community_code_5;
ALTER TABLE communities DROP INDEX community_code_6;
ALTER TABLE communities DROP INDEX community_code_7;
ALTER TABLE communities DROP INDEX community_code_8;
ALTER TABLE communities DROP INDEX community_code_9;
ALTER TABLE communities DROP INDEX community_code_10;
ALTER TABLE communities DROP INDEX community_code_11;
ALTER TABLE communities DROP INDEX community_code_12;
ALTER TABLE communities DROP INDEX community_code_13;
ALTER TABLE communities DROP INDEX community_code_14;
ALTER TABLE communities DROP INDEX community_code_15;
ALTER TABLE communities DROP INDEX community_code_16;
ALTER TABLE communities DROP INDEX community_code_17;
ALTER TABLE communities DROP INDEX community_code_18;
ALTER TABLE communities DROP INDEX community_code_19;
ALTER TABLE communities DROP INDEX community_code_20;
ALTER TABLE communities DROP INDEX community_code_21;
ALTER TABLE communities DROP INDEX community_code_22;
ALTER TABLE communities DROP INDEX community_code_23;
ALTER TABLE communities DROP INDEX community_code_24;
ALTER TABLE communities DROP INDEX community_code_25;
ALTER TABLE communities DROP INDEX community_code_26;
ALTER TABLE communities DROP INDEX community_code_27;
ALTER TABLE communities DROP INDEX community_code_28;
ALTER TABLE communities DROP INDEX community_code_29;
ALTER TABLE communities DROP INDEX community_code_30;
ALTER TABLE communities DROP INDEX community_code_31;
ALTER TABLE communities DROP INDEX community_code_32;
ALTER TABLE communities DROP INDEX community_code_33;
ALTER TABLE communities DROP INDEX community_code_34;
ALTER TABLE communities DROP INDEX community_code_35;
ALTER TABLE communities DROP INDEX community_code_36;
ALTER TABLE communities DROP INDEX community_code_37;
ALTER TABLE communities DROP INDEX community_code_38;
ALTER TABLE communities DROP INDEX community_code_39;
ALTER TABLE communities DROP INDEX community_code_40;
ALTER TABLE communities DROP INDEX community_code_41;
ALTER TABLE communities DROP INDEX community_code_42;
ALTER TABLE communities DROP INDEX community_code_43;
ALTER TABLE communities DROP INDEX community_code_44;
ALTER TABLE communities DROP INDEX community_code_45;
ALTER TABLE communities DROP INDEX community_code_46;
ALTER TABLE communities DROP INDEX community_code_47;
ALTER TABLE communities DROP INDEX community_code_48;
ALTER TABLE communities DROP INDEX community_code_49;
ALTER TABLE communities DROP INDEX community_code_50;
ALTER TABLE communities DROP INDEX community_code_51;
ALTER TABLE communities DROP INDEX community_code_52;
ALTER TABLE communities DROP INDEX community_code_53;
ALTER TABLE communities DROP INDEX community_code_54;
ALTER TABLE communities DROP INDEX community_code_55;
ALTER TABLE communities DROP INDEX community_code_56;
ALTER TABLE communities DROP INDEX community_code_57;
ALTER TABLE communities DROP INDEX community_code_58;
ALTER TABLE communities DROP INDEX community_code_59;
ALTER TABLE communities DROP INDEX community_code_60;
ALTER TABLE communities DROP INDEX community_code_61;
ALTER TABLE communities DROP INDEX community_code_62;

-- Drop duplicate foreign key constraints (keep only the first one)
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_2;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_3;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_4;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_5;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_6;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_7;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_8;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_9;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_10;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_11;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_12;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_13;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_14;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_15;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_16;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_17;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_18;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_19;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_20;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_21;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_22;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_23;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_24;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_25;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_26;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_27;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_28;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_29;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_30;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_31;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_32;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_33;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_34;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_35;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_36;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_37;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_38;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_39;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_40;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_41;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_42;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_43;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_44;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_45;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_46;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_47;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_48;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_49;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_50;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_51;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_52;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_53;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_54;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_55;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_56;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_57;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_58;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_59;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_60;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_61;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_62;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_63;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_64;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_65;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_66;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_67;
ALTER TABLE communities DROP FOREIGN KEY communities_ibfk_68;

-- Verify the final structure
SHOW CREATE TABLE communities;

SELECT 'Communities table indexes and constraints have been cleaned up successfully!' as Result;